### ISSUE TITLE
Please make a firmware for stm32, which will communicate with the ROS via the rosserial, like in turtlebot3

### ISSUE THREAD

**Issue by amburkoff** [isabellesimova/HoverboardFirmware#7]
Please make a firmware for stm32, which will communicate with the ROS via the rosserial, like here in turtlebot3 [http://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup](http://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup) .
About rosserial and the protocol of communication between the openCR and the raspberry pi can be read here [http://community.robotsource.org/t/download-the-ros-robot-programming-book-for-free/51](http://community.robotsource.org/t/download-the-ros-robot-programming-book-for-free/51)
It is necessary that the data on the odom and imu arrive correctly.

**Comment by isabellesimova** [comment]
Hi! I don't plan on supporting ROS, but you're more than welcome to fork the project and implement it yourself :)
